[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate && python manage.py runserver 0.0.0.0:$PORT"
healthcheckPath = "/api/auth/health/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"

[services.variables]
PORT = "8000"
